//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_vente
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_vente
    {
        public int id_vente { get; set; }
        public int id_produit { get; set; }
        public int quantite { get; set; }
    
        public virtual produit produit { get; set; }
        public virtual vente vente { get; set; }
    }
}
