//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_vente
{
    using System;
    using System.Collections.Generic;
    
    public partial class produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produit()
        {
            this.detail_vente = new HashSet<detail_vente>();
        }
    
        public int id_produit { get; set; }
        public string nom_produit { get; set; }
        public string ppv { get; set; }
        public string pph { get; set; }
        public int stock { get; set; }
        public int id_categorie { get; set; }
    
        public virtual categorie categorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detail_vente> detail_vente { get; set; }
    }
}
